# Generated by Django 2.2.3 on 2019-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=120, verbose_name='College Name')),
                ('courses', models.CharField(max_length=120, verbose_name='Courses Avialable')),
                ('address', models.CharField(max_length=120)),
                ('fees', models.TextField(blank=True)),
            ],
        ),
    ]
