# Generated by Django 2.2.3 on 2019-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='courses',
            field=models.CharField(max_length=120, verbose_name='Courses Available'),
        ),
    ]
