# Generated by Django 2.2.3 on 2019-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_auto_20190728_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='marks',
            field=models.IntegerField(default='50'),
        ),
    ]
