# Generated by Django 2.2.3 on 2019-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0003_colleges_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
