# Generated by Django 2.2.3 on 2019-07-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='college',
            new_name='colleges',
        ),
    ]
