# Generated by Django 2.2.3 on 2019-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0007_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='colleges',
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.CharField(max_length=120, null=True, verbose_name='Exam Required'),
        ),
    ]
