# Generated by Django 2.2.4 on 2019-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0008_auto_20190825_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', models.TextField(max_length=120, verbose_name='Content')),
            ],
        ),
    ]
