# Generated by Django 2.2.4 on 2019-09-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0010_auto_20190924_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
